cryptoMainApp/app/user/forms/__init__.py
from flask_wtf import FlaskForm
from wtforms import FloatField, RadioField, StringField
from wtforms.validators import InputRequired


class AccountBalanceForm(FlaskForm):
    card_number = StringField('Card number')
    amount = FloatField('Amount', validators=[InputRequired()])
    cvc_number = StringField('CVC')
    type = RadioField('Transaction', choices=[
        ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('withdraw_all', 'Withdraw all')
    ], default='deposit')

cryptoMainApp/app/user/__init__.py
from flask import Blueprint


user_blueprint = Blueprint('user', __name__, template_folder='templates')

cryptoMainApp/app/user/utils/__init__.py
from typing import Dict, Set, List

from app.auth.models import User
from app.utils.constans import NAME_CODE_MAPPING


class UserDataModel:
    def __init__(self, user_model: User):
        self.user_model: User = user_model

    def _get_account_info(self) -> Dict:
        temp_dict: Dict = dict()
        temp_dict['created_at']: str = self.user_model.created_at.strftime("%m.%d.%Y %H:%M:%S")
        temp_dict['email']: str = self.user_model.email
        temp_dict['username']: str = self.user_model.username
        return temp_dict

    def _get_wallet_info(self) -> Dict:
        temp_dict: Dict = dict()
        temp_dict['in-house']: float = round(self.user_model.wallet.inhouse_currency, 3)
        temp_dict['crypto']: List = []
        all_currencies_set: Set = set(NAME_CODE_MAPPING.keys())
        for crypto in self.user_model.wallet.currencies:
            all_currencies_set.remove(crypto.currency.name)
            temp_dict['crypto'].append(
                {
                    'amount': round(crypto.amount, 3),
                    'name': crypto.currency.name,
                    'code': crypto.currency.code
                }
            )

        for crypto in all_currencies_set:
            temp_dict['crypto'].append(
                {
                    'amount': 0.0,
                    'name': crypto,
                    'code': NAME_CODE_MAPPING[crypto]
                }
            )

        return temp_dict

    def _get_transaction_history(self) -> List:
        temp_list: List = []
        for index, transaction in enumerate(self.user_model.wallet.transaction_history, start=1):
            temp_list.append(
                {
                    'id': index,
                    'amount': transaction.amount,
                    'name': transaction.currency.name,
                    'code': transaction.currency.code,
                    'price_at_transaction': transaction.current_price,
                    'transaction_date': transaction.date.strftime("%m.%d.%Y %H:%M:%S"),
                    'operation_type': transaction.operation_type,
                    'total_cost': transaction.total_cost
                }
            )
        return temp_list

    def extract_data(self) -> Dict:
        return {'user': self._get_account_info(),
                'wallet': self._get_wallet_info(),
                'transaction_history': self._get_transaction_history()
                }


class AccountBalanceModel:
    def __init__(self, user_model: User):
        self.user_model: User = user_model

    def _get_money_state(self) -> float:
        return round(self.user_model.wallet.inhouse_currency, 3)

    def _get_top_ups_history(self) -> List:
        temp_list: List = []
        for index, transaction in enumerate(self.user_model.wallet.wallet_top_up, start=1):
            temp_list.append(
                {
                    'id': index,
                    'amount': transaction.amount,
                    'transaction_date': transaction.date.strftime("%m.%d.%Y %H:%M:%S"),
                    'operation_type': transaction.operation_type,
                }
            )
        return temp_list

    def extract_data(self) -> Dict:
        return {
            'state': self._get_money_state(),
            'top_ups': self._get_top_ups_history()
        }

cryptoMainApp/app/user/views/__init__.py
from typing import Dict

from flask import render_template, flash
from flask_login import login_required, current_user

from app.user import user_blueprint
from app.utils.prepare_data import prepare_images_links
from app.user.utils import UserDataModel, AccountBalanceModel
from app.user.forms import AccountBalanceForm
from app.extensions import db
from app.trading.models import WalletTopUp


@user_blueprint.route('/account')
@login_required
def account_view():
    user: UserDataModel = UserDataModel(current_user)
    output_model: Dict = user.extract_data()
    return render_template('account.html', images=prepare_images_links(), output=output_model)


@user_blueprint.route('/account/balance', methods=['POST', 'GET'])
@login_required
def balance_view():
    account_balance: AccountBalanceModel = AccountBalanceModel(current_user)

    account_balance_form = AccountBalanceForm()

    if account_balance_form.validate_on_submit():
        operation_type = account_balance_form.type.data
        amount = account_balance_form.amount.data

        if operation_type == 'withdraw_all':
            amount = current_user.wallet.inhouse_currency
            operation_type = 'withdraw'
            current_user.wallet.inhouse_currency = 0
            db.session.add(current_user)

        else:
            if amount <= 0:
                flash('Incorrect value')
                return render_template('balance.html', form=account_balance_form,
                                       output_model=account_balance.extract_data())

            if operation_type == 'withdraw':
                if current_user.wallet.inhouse_currency < amount:
                    flash("You don't have enough money to withdraw")
                    return render_template('balance.html', form=account_balance_form,
                                           output_model=account_balance.extract_data())

                current_user.wallet.inhouse_currency -= amount
                db.session.add(current_user)

            else:
                current_user.wallet.inhouse_currency += amount
                db.session.add(current_user)

        wallet_top_up = WalletTopUp(operation_type=operation_type, amount=amount, wallet_id=current_user.wallet.id)
        db.session.add(wallet_top_up)
        db.session.commit()

    account_balance_form.amount.data = 0.0
    account_balance_form.amount.raw_data = ['0.0']
    return render_template('balance.html', form=account_balance_form, output_model=account_balance.extract_data())

cryptoMainApp/app/user/templates/account.html
{% extends "base.html" %}

{% macro build_list_item(id, wallet, images) -%}
<li class="list-group-item">
    <div class="row align-items-center">
        <div class="col-2">
            <img class="card-img-top"
                 src="{{ url_for('static', filename=images[wallet[id]['name']]) }}"
                 alt="{{ wallet[id]['name'] }} logo"
                 style="width: 2rem; height: 2rem;">
        </div>
        <div class="col-3">{{ wallet[id]['name'] }}</div>
        <div class="col-2">{{ wallet[id]['code'] }}</div>
        <div class="col-2"><b>{{ wallet[id]['amount'] }}</b></div>
        <div class="col-3"><a href="{{ url_for('trading.currency_info_view', code=wallet[id]['code']) }}" class="btn btn-secondary btn-sm">Buy or Sell</a></div>
    </div>
</li>
{%- endmacro %}

{% block content_block %}

    {% set user = output['user'] %}
    {% set in_house = output['wallet']['in-house'] %}
    {% set wallet = output['wallet']['crypto'] %}
    {% set transaction_history = output['transaction_history'] %}

    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                        aria-controls="panelsStayOpen-collapseOne">
                    <b>User information</b>
                </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                 aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    <div class="row mx-0">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <div class="card-body">
                                <h5 class="card-title">{{ user['username'] }}</h5>
                                <p class="card-text">Username</p>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">{{ user['email'] }}</h5>
                                <p class="card-text">Email</p>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">{{ user['created_at'] }}</h5>
                                <p class="card-text">Created at</p>
                            </div>

                        </div>
                        <div class="col-6 align-self-center">
                            <div class="card-body">
                                <h5 class="card-title">{{ in_house }}$</h5>
                                <p class="card-text">In-house</p>
                                <a href="{{ url_for('user.balance_view') }}" class="btn btn-secondary btn-sm">Balance</a>
                            </div>
                        </div>
                        <div class="col-1"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseTwo">
                    <b>User Wallet</b>
                </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                    <div class="row mx-0">

                        <div class="col-12 col-lg-6 px-lg-0 col-xl-4">

                            <ul class="list-group list-group-flush">
                                {{  build_list_item(0, wallet, images) }}
                                {{  build_list_item(1, wallet, images) }}
                                {{  build_list_item(2, wallet, images) }}
                                {{  build_list_item(3, wallet, images) }}
                                {{  build_list_item(4, wallet, images) }}
                            </ul>

                        </div>
                        <div class="col-12 col-lg-6 px-lg-0 col-xl-4">

                            <ul class="list-group list-group-flush">
                                {{  build_list_item(5, wallet, images) }}
                                {{  build_list_item(6, wallet, images) }}
                                {{  build_list_item(7, wallet, images) }}
                                {{  build_list_item(8, wallet, images) }}
                                {{  build_list_item(9, wallet, images) }}
                            </ul>

                        </div>
                        <div class="col-12 col-lg-12 px-lg-0 col-xl-4">

                            <ul class="list-group list-group-flush">
                                {{  build_list_item(10, wallet, images) }}
                                {{  build_list_item(11, wallet, images) }}
                                {{  build_list_item(12, wallet, images) }}
                                {{  build_list_item(13, wallet, images) }}
                                {{  build_list_item(14, wallet, images) }}
                            </ul>
                        </div>

                    </div>


                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseThree">
                    <b>Transaction history</b>
                </button>
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingThree">
                <div class="accordion-body">
                    <div class="row mx-0">
                        <div class="col-12">

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th class="d-none d-md-table-cell" scope="col">Code</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Cost</th>
                                    <th class="d-none d-md-table-cell" scope="col">Type</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in transaction_history %}
                                    <tr>
                                        <th scope="row">{{ item['id'] }}</th>
                                        <td>{{ item['name'] }}</td>
                                        <td class="d-none d-md-table-cell">{{ item['code'] }}</td>
                                        <td>{{ item['amount'] }}</td>
                                        <td>{{ item['price_at_transaction'] }}$</td>
                                        <td>{{ item['total_cost'] }}$</td>
                                        <td class="d-none d-md-table-cell">{{ item['operation_type'] }}</td>
                                        <td>{{ item['transaction_date'] }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cryptoMainApp/app/user/templates/balance.html
{% extends "base.html" %}

{% block content_block %}

    {% set top_ups_history = output_model['top_ups'] %}
    {% set state = output_model['state'] %}

    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                        aria-controls="panelsStayOpen-collapseOne">
                    <b>User information</b>
                </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                 aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    <div class="row mx-0">
                        <div class="col-3"></div>
                        <div class="col-3">
                            <div class="card-body mt-5">
                                <h5 class="card-title">{{ state }}$</h5>
                                <p class="card-text">Current state</p>
                            </div>
                        </div>
                        <div class="col-4">
                            <form method="POST"
                                  action="{{ url_for('user.balance_view') }}">
                                {{ form.csrf_token }}

                                <div class="mb-1">
                                    {{ form.card_number.label(class="form-label") }}
                                    {{ form.card_number(class="form-control") }}
                                </div>

                                <div class="mb-1">
                                    <div class="row">
                                        <div class="col-4">
                                            {{ form.cvc_number.label(class="form-label") }}
                                            {{ form.cvc_number(class="form-control") }}
                                        </div>
                                        <div class="col-8">
                                            {{ form.amount.label(class="form-label") }}
                                            {{ form.amount(class="form-control") }}
                                        </div>
                                    </div>
                                </div>

                                {% for subfield in form.type %}
                                    <div class="form-check form-check-inline">
                                        {{ subfield.label(class="form-check-label") }}
                                        {{ subfield(class="form-check-input") }}
                                    </div>
                                {% endfor %}

                                <div class="mb-1">
                                    {% with messages = get_flashed_messages() %}
                                        {% if messages %}
                                            <div class="alert alert-danger" role="alert">
                                                {% for message in messages %}
                                                    {{ message }}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    {% endwith %}
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-secondary"> Submit</button>
                                </div>
                            </form>

                        </div>
                        <div class="col-2"></div>
                    </div>
                </div>
            </div>
        </div>


        {#        <div class="accordion-item">#}
        {#            <h2 class="accordion-header" id="panelsStayOpen-headingOne">#}
        {#                <button class="accordion-button" type="button" data-bs-toggle="collapse"#}
        {#                        data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"#}
        {#                        aria-controls="panelsStayOpen-collapseOne">#}
        {#                    <b>User information</b>#}
        {#                </button>#}
        {#            </h2>#}
        {#            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"#}
        {#                 aria-labelledby="panelsStayOpen-headingOne">#}
        {#                <div class="accordion-body">#}
        {#                    <div class="row mx-0">#}
        {#                        <div class="col-2"></div>#}
        {#                        <div class="col-4">#}
        {#                            <div class="card-body">#}
        {#                                <h5 class="card-title">{{ user['username'] }}</h5>#}
        {#                                <p class="card-text">Username</p>#}
        {#                            </div>#}
        {##}
        {#                            <div class="card-body">#}
        {#                                <h5 class="card-title">{{ user['email'] }}</h5>#}
        {#                                <p class="card-text">Email</p>#}
        {#                            </div>#}
        {##}
        {#                            <div class="card-body">#}
        {#                                <h5 class="card-title">{{ user['created_at'] }}</h5>#}
        {#                                <p class="card-text">Created at</p>#}
        {#                            </div>#}
        {##}
        {#                        </div>#}
        {#                        <div class="col-6 align-self-center">#}
        {#                            <div class="card-body">#}
        {#                                <h5 class="card-title">{{ in_house }}$</h5>#}
        {#                                <p class="card-text">In-house</p>#}
        {#                                <a class="btn btn-secondary btn-sm">Withdraw</a>#}
        {#                                <a class="btn btn-secondary btn-sm">Deposit</a>#}
        {#                            </div>#}
        {#                        </div>#}
        {#                        <div class="col-1"></div>#}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseThree">
                    <b>Transaction history</b>
                </button>
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingThree">
                <div class="accordion-body">
                    <div class="row mx-0">
                        <div class="col-12">

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in top_ups_history %}
                                    <tr>
                                        <th scope="row">{{ item['id'] }}</th>
                                        <td>{{ item['amount'] }}</td>
                                        <td>{{ item['operation_type'] }}</td>
                                        <td>{{ item['transaction_date'] }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}