cryptoMainApp/app/pages/forms/__init__.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, TextAreaField
from wtforms.validators import InputRequired, Email, Length


class MessageForm(FlaskForm):
    name = StringField('Name')
    surname = StringField('Surname')
    email = EmailField('Email', validators=[InputRequired(), Email()])
    message = TextAreaField(validators=[Length(max=512)])

    def reset_fields(self):
        self.name.data = ''
        self.surname.data = ''
        self.email.data = ''
        self.message.data = ''

cryptoMainApp/app/pages/__init__.py
from flask import Blueprint


pages_blueprint = Blueprint('pages', __name__, template_folder='templates')

cryptoMainApp/app/pages/views/__init__.py
from flask import flash, render_template, request
from flask_login import current_user

from app.pages import pages_blueprint
from app.pages.forms import MessageForm


@pages_blueprint.route('/')
@pages_blueprint.route('/home')
def home_view():
    return render_template('home.html')


@pages_blueprint.route('/contact', methods=['POST', 'GET'])
def contact_view():
    message_form = MessageForm()
    if message_form.validate_on_submit():
        name = request.form.get('name')
        surname = request.form.get('surname')
        email = request.form.get('email')
        message = request.form.get('message')

        # Prepare email

        flash('Email has been sent, thank you!')
        message_form.reset_fields()
    if current_user.is_authenticated:
        message_form.email.data = current_user.email
    return render_template('contact.html', form=message_form)

cryptoMainApp/app/pages/templates/contact.html
{% extends "base.html" %}
{% block content_block %}

    <div class="container">
        <div class="row mt-5">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="row mt-5">
                    <div class="col-0 col-lg-6 d-none d-lg-block">
                        <img src="{{ url_for('static', filename='images/pages/message.svg') }}" class="img-fluid"
                             alt="...">
                    </div>
                    <div class="col-12 col-lg-6">
                        <form method="POST" action="{{ url_for('pages.contact_view') }}">
                            {{ form.csrf_token }}

                            <div class="mb-3">
                                {{ form.name.label(class="form-label") }}
                                {{ form.name(class="form-control") }}
                                {% if form.name.errors %}
                                    <ul class="errors">
                                        {% for error in form.name.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                {{ form.surname.label(class="form-label") }}
                                {{ form.surname(class="form-control") }}
                                {% if form.surname.errors %}
                                    <ul class="errors">
                                        {% for error in form.surname.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                {{ form.email.label(class="form-label") }}
                                {{ form.email(class="form-control") }}
                                {% if form.email.errors %}
                                    <ul class="errors">
                                        {% for error in form.email.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                {{ form.message.label(class="form-label") }}
                                {{ form.message(class="form-control") }}
                                {% if form.message.errors %}
                                    <ul class="errors">
                                        {% for error in form.message.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                {% with messages = get_flashed_messages() %}
                                    {% if messages %}
                                        <div class="alert alert-info" role="alert">
                                            {% for message in messages %}
                                                {{ message }}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                {% endwith %}
                            </div>

                            <button type="submit" class="btn btn-secondary">Send</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>

{% endblock %}

cryptoMainApp/app/pages/templates/home.html
{% extends "base.html" %}
{% block content_block %}

    <div class="container">
        <div class="row mt-3">
            <div class="col-1"></div>
            <div class="col-10">

                <div class="row">
                    <div class="col-lg-11 col-md-12">
                        <div class="card mb-1 border-0" style="max-width: 60rem;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="{{ url_for('static', filename='images/pages/payment.svg') }}"
                                         class="img-fluid mx-auto d-block rounded-start"
                                         style="width: 12rem; height: 14rem;">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">Easy and convenient payment</h5>
                                        <p class="card-text">Bacon ipsum dolor amet hamburger pastrami corned beef rump
                                            capicola shankle pork belly prosciutto strip steak boudin drumstick jerky.
                                            Picanha short ribs swine pig cow, burgdoggen jerky shankle short loin tail
                                            boudin buffalo.</p>
                                        <p class="card-text">Cupim alcatra tongue kevin t-bone, pork tenderloin
                                            turducken short loin. Corned beef meatball pork belly venison. Landjaeger
                                            frankfurter jerky ground round pork chop bacon kielbasa pastrami pancetta
                                            jowl pig beef hamburger short ribs.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-1 col-md-0"></div>
                </div>

                <div class="row">
                    <div class="col-lg-1 col-md-0"></div>
                    <div class="col-lg-11 col-md-12">
                        <div class="card mb-1 border-0" style="max-width: 60rem;">
                            <div class="row g-0">

                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">Forecasting the currency rate</h5>
                                        <p class="card-text">Bacon ipsum dolor amet hamburger pastrami corned beef rump
                                            capicola shankle pork belly prosciutto strip steak boudin drumstick jerky.
                                            Picanha short ribs swine pig cow, burgdoggen jerky shankle short loin tail
                                            boudin buffalo.</p>
                                        <p class="card-text">Cupim alcatra tongue kevin t-bone, pork tenderloin
                                            turducken short loin. Corned beef meatball pork belly venison. Landjaeger
                                            frankfurter jerky ground round pork chop bacon kielbasa pastrami pancetta
                                            jowl pig beef hamburger short ribs.</p>
                                    </div>
                                </div>
                                <div class="col-md-4">

                                    <img src="{{ url_for('static', filename='images/pages/data_trends.svg') }}"
                                         class="img-fluid mx-auto d-block rounded-start"
                                         style="width: 12rem; height: 14rem;">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-11 col-md-12">
                        <div class="card mb-1 border-0" style="max-width: 60rem;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="{{ url_for('static', filename='images/pages/respond.svg') }}"
                                         class="img-fluid mx-auto d-block rounded-start"
                                         style="width: 12rem; height: 14rem;">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">Quick and easy contact with our specialists</h5>
                                        <p class="card-text">Bacon ipsum dolor amet hamburger pastrami corned beef rump
                                            capicola shankle pork belly prosciutto strip steak boudin drumstick jerky.
                                            Picanha short ribs swine pig cow, burgdoggen jerky shankle short loin tail
                                            boudin buffalo.</p>
                                        <p class="card-text">Cupim alcatra tongue kevin t-bone, pork tenderloin
                                            turducken short loin. Corned beef meatball pork belly venison. Landjaeger
                                            frankfurter jerky ground round pork chop bacon kielbasa pastrami pancetta
                                            jowl pig beef hamburger short ribs.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-1 col-md-0"></div>
                </div>

            </div>
            <div class="col-1"></div>
        </div>
    </div>
{% endblock %}